name: Code Coverage for jvgraph

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -e .[dev]

      - name: Run Pytest with Coverage
        run: |
          pytest --cov=jvgraph --cov-report=xml --cov-report=term-missing
          coverage report --show-missing

      - name: Run Coverage Check
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: 0.99
